class CfgPatches
{
	class Tshirt_Uniforms
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F"
		};
	};
};
class CfgVehicleClasses
{
	class Tshirt_BDU
	{
		displayName="Tshirt";
	};
};
class cfgFactionClasses
{
	class Tshirt
	{
		displayName="Tshirt";
		priority=1;
		side=1;
	};
};
class CfgVehicles
{
	class B_Soldier_F;
	class TShirt_01: B_Soldier_F
	{
		scope=2;
		displayName="T shirt G3 (Tan)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_Tan";
		model="\t_shirt\t_shirt\tshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_tan_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_02: B_Soldier_F
	{
		scope=2;
		displayName="T shirt G3 (Black)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_blk";
		model="\t_shirt\t_shirt\tshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_03: B_Soldier_F
	{
		scope=2;
		displayName="T shirt G3 (Oakley)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_blk_1";
		model="\t_shirt\t_shirt\tshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_oakley_1_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_04: B_Soldier_F
	{
		scope=2;
		displayName="T shirt G3 Oakley (Black)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_blk_2";
		model="\t_shirt\t_shirt\tshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_oakley_2_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_05: B_Soldier_F
	{
		scope=2;
		displayName="T shirt Cargos";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_blk_3";
		model="\t_shirt\t_shirt\tshirt_3.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_beige_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_grey_creepin_co.paa",
			""
		};
	};
	class TShirt_06: B_Soldier_F
	{
		scope=2;
		displayName="T shirt G3 BUDS (Navy)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_BUDS";
		model="\t_shirt\t_shirt\tshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_navy_udt_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class PShirt_01: B_Soldier_F
	{
		scope=2;
		displayName="Poloshirt G3 (Tan)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="poloshirt_Tan";
		model="\t_shirt\t_shirt\poloshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class PShirt_02: B_Soldier_F
	{
		scope=2;
		displayName="Poloshirt G3 2 (Tan)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="poloshirt_Tan_2";
		model="\t_shirt\t_shirt\poloshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_od_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class PShirt_03: B_Soldier_F
	{
		scope=2;
		displayName="Poloshirt G3 1 (OD)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="poloshirt_OD";
		model="\t_shirt\t_shirt\poloshirt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_od_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_navy_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_V_1: B_Soldier_F
	{
		scope=2;
		displayName="T shirt Velro G3 (Tan)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_V_Tan";
		model="\t_shirt\t_shirt\tshirt_2.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_tan_v_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt_v.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class Jeans_01: B_Soldier_F
	{
		scope=2;
		displayName="Jeans Blue Tshirt";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Jeans_Tan";
		model="\t_shirt\t_shirt\jeans.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\jeans_blue_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\jeans.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
	};
	class TShirt_C_1: B_Soldier_F
	{
		scope=2;
		displayName="T shirt Cargos (OD)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_CARGO_1";
		model="\t_shirt\t_shirt\tshirt_3.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_green_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_grey_dirty_creepin_co.paa",
			""
		};
	};
	class TShirt_C_2: B_Soldier_F
	{
		scope=2;
		displayName="T shirt OD Cargos (OD)";
		vehicleClass="Tshirt_BDU";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Tshirt_CARGO_2";
		model="\t_shirt\t_shirt\tshirt_3.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"",
			""
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_green_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_od_creepin_co.paa",
			""
		};
	};
	class Jeans_02: B_Soldier_F
	{
		scope=2;
		displayName="Jeans Blue with shirt";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_diver"
		};
		faction="Tshirt";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="Jeans_Shirt";
		model="\t_shirt\t_shirt\jeans_2.p3d";
		hiddenSelections[]=
		{
			""
		};
		hiddenSelectionsTextures[]=
		{
			""
		};
		hiddenSelectionsMaterials[]=
		{
			""
		};
	};
};
class cfgWeapons
{
	class Uniform_Base;
	class UniformItem;
	class Tshirt_Tan: Uniform_Base
	{
		scope=2;
		displayName="T shirt Tan G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_tan_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_01";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_blk: Uniform_Base
	{
		scope=2;
		displayName="T shirt Black G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_02";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_blk_1: Uniform_Base
	{
		scope=2;
		displayName="T shirt Black Oakley 1 G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_oakley_1_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_03";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_blk_2: Uniform_Base
	{
		scope=2;
		displayName="T shirt Black Oakley 2 G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_blk_oakley_2_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_04";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_blk_3: Uniform_Base
	{
		scope=2;
		displayName="T shirt Cargo (grey) ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_beige_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_grey_creepin_co.paa",
			""
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_05";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_BUDS: Uniform_Base
	{
		scope=2;
		displayName="T shirt BUDS G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_navy_udt_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_06";
			containerClass="Supply20";
			mass=50;
		};
	};
	class poloshirt_Tan: Uniform_Base
	{
		scope=2;
		displayName="Poloshirt Tan G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="PShirt_01";
			containerClass="Supply20";
			mass=50;
		};
	};
	class poloshirt_Tan_2: Uniform_Base
	{
		scope=2;
		displayName="Poloshirt Tan 2 G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_od_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="PShirt_02";
			containerClass="Supply20";
			mass=50;
		};
	};
	class poloshirt_OD: Uniform_Base
	{
		scope=2;
		displayName="Poloshirt Tan 2 G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_od_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_navy_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="PShirt_03";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_V_Tan: Uniform_Base
	{
		scope=2;
		displayName="T shirt Tan Velcro G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\crye_g3_tan_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_tan_v_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\crye_g3.rvmat",
			"\t_shirt\t_shirt\data\tshirt_v.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_V_1";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Jeans_Tan: Uniform_Base
	{
		scope=2;
		displayName="Jeans Tan G3 ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\jeans_blue_co.paa",
			"\t_shirt\t_shirt\tex\poloshirt_sand_co.paa",
			"\t_shirt\t_shirt\tex\TAN_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\t_shirt\t_shirt\data\jeans.rvmat",
			"\t_shirt\t_shirt\data\poloshirt_velcro.rvmat",
			"\t_shirt\t_shirt\data\gloves.rvmat"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="Jeans_01";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_CARGO_1: Uniform_Base
	{
		scope=2;
		displayName="T shirt Grey Creepin Cargos (OD) ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"",
			""
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_green_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_grey_dirty_creepin_co.paa",
			""
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_C_1";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Tshirt_CARGO_2: Uniform_Base
	{
		scope=2;
		displayName="T shirt Green Creepin Cargos (OD) ";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"",
			""
		};
		hiddenSelectionsTextures[]=
		{
			"\t_shirt\t_shirt\tex\cargopants_green_co.paa",
			"\t_shirt\t_shirt\tex\tshirt_od_creepin_co.paa",
			""
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TShirt_C_2";
			containerClass="Supply20";
			mass=50;
		};
	};
	class Jeans_Shirt: Uniform_Base
	{
		scope=2;
		displayName="Jeans UKSF Nairobi";
		picture="\t_shirt\t_shirt\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			""
		};
		hiddenSelectionsMaterials[]=
		{
			""
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="Jeans_02";
			containerClass="Supply20";
			mass=50;
		};
	};
};
class cfgMods
{
	author="Road Runner";
	timepacked="1549119900";
};
