class CfgVehicles
{
	class B_Soldier_F;
	class B_diver_F;
	class tfl_puff_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\northface_blk_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_puff_s_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_puff_s_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_puff_s_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_puff_s_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_puff_s_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_puff_s_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_northface_g.p3d";
		uniformClass="tfl_puff_s_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\northface_sand_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\pcu_grey_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_b_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_b_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_b_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_b_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_b_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_b_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_b_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\pcu_black_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mca_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mca_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mca_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\pcu_mca_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_mc_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mc_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mc_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mc_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mc_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_mc_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_mc_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\pcu_multicam_co.paa",
			"TFL_cold\data\gunglove_grey_co.paa"
		};
	};
	class tfl_pcu_brown_mc_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_mc_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_g3\g3\pants_mc.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_brown_aor1_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_aor1_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_g3\g3\pants_aor1.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_brown_aor2_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_aor2_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_g3\g3\pants_aor2.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_brown_mca_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_mca_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_g3\g3\pants_mca.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_brown_m81_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_m81_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_g3\g3\pants_m81.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
	class tfl_pcu_brown_mcal_g: B_Soldier_F
	{
		scope=1;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=0;
		faction="sof_rangers";
		author="TFL";
		model="tfl_cold\tfl_pcu_g.p3d";
		uniformClass="tfl_pcu_brown_mcal_g_uniform";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"rightknee",
			"leftknee",
			"camo1",
			"glove"
		};
		hiddenSelectionsTextures[]=
		{
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_g3\g3\pants_mcal.paa",
			"tfl_cold\data\pcu_brown_co.paa",
			"TFL_cold\data\gunglove_co.paa"
		};
	};
};