class OPSCORE(puotek) : TAG(core) {
    scope=2;
    displayName="Ops-Core MT Puotek";
    model="\121_75th_helmet\75th_opscore1.p3d";
    hiddenSelections[]={
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_pvs31Batt",
        "_Switch"
    };
    hiddenSelectionsMaterials[]={
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\accs\amp\amp2.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]={
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        PATCH(nya),
        PATCH(fixstupid),
        "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    ace_arsenal_hide = 1;
    ace_arsenal_uniqueBase = Q(OPSCORE(puotek_off));
    class ItemInfo : ItemInfo {
        uniformModel="\121_75th_helmet\75th_opscore1.p3d";
        hiddenSelections[]={
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_pvs31Batt",
            "_Switch"
        };
    };
};

class OPSCORE(puotek_off) : OPSCORE(puotek) {
    displayName="Ops-Core MT Puotek Folded";
    model="\121_75th_helmet\75th_opscore1_off.p3d";
    EHP_OFF;
    ace_arsenal_hide = 0;
    ace_arsenal_uniqueBase = "";
    class ItemInfo: ItemInfo {
        uniformModel="\121_75th_helmet\75th_opscore1_off.p3d";
    };
};


/////////OLD/////////fixme
/*
class aa_opscore_muscle: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Muscle Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_com_PS.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "_patch",
        "_patch2"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat"
    };
    hiddenSelectionsTextures[]=
    {
        "aa_121_helmets\data\patch_aa_co.paa",
        "aa_121_helmets\data\patch_aa_muscle_co.paa"
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_com_PS.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "_patch",
            "_patch2"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat"
        };
        hiddenSelectionsTextures[]=
        {
            "aa_121_helmets\data\patch_aa_co.paa",
            "aa_121_helmets\data\patch_aa_muscle_co.paa"
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_muscle_off: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Muscle Special' (Headset off)";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_counterWeight",
        "_Switch",
        "_strobe01"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\accs\amp\amp2.rvmat",
        "",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_co.paa",
        "aa_121_helmets\data\patch_aa_muscle_co.paa",
        "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
        "",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_counterWeight",
            "_Switch",
            "_strobe01"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\accs\amp\amp2.rvmat",
            "",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_co.paa",
            "aa_121_helmets\data\patch_aa_muscle_co.paa",
            "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
            "",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_muscle_stowed: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Muscle Special' (Stowed)";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_com_1PL_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Cap, Stowed Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "_counterweight",
        "_patch",
        "_patch2"
    };
    hiddenSelectionsMaterials[]=
    {
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat"
    };
    hiddenSelectionsTextures[]=
    {
        "",
        "aa_121_helmets\data\patch_aa_co.paa",
        "aa_121_helmets\data\patch_aa_muscle_co.paa"
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_com_1PL_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "_strobe01",
            "_patch",
            "_patch2"
        };
        hiddenSelectionsMaterials[]=
        {
            "",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat"
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_egg: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Egg Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_peltor2.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_HelmetCam",
        "_pvs31Batt"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_eggv2_co.paa",
        "aa_121_helmets\data\patch_aa_est_ir_rev_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_peltor2.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_HelmetCam",
            "_pvs31Batt"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_eggv2_co.paa",
            "aa_121_helmets\data\patch_aa_est_ir_rev_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_egg_off: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Egg Special' (Headset off)";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_peltor2_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_HelmetCam",
        "_pvs31Batt"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_eggv2_co.paa",
        "aa_121_helmets\data\patch_aa_est_ir_rev_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_peltor2_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_HelmetCam",
            "_pvs31Batt"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_eggv2_co.paa",
            "aa_121_helmets\data\patch_aa_est_ir_rev_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_wacc: ItemCore
{
    author="soupie von soup";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Wacc Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_com_XO.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset, Miku :DDD";
    hiddenSelections[]=
    {
        "_strobe01",
        "_patch",
        "_patch2"
    };
    hiddenSelectionsMaterials[]=
    {
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat"
    };
    hiddenSelectionsTextures[]=
    {
        "",
        "aa_121_helmets\data\patch_aa_est_ir_co.paa",
        "aa_121_helmets\data\patch_aa_pj_co.paa"
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_com_XO.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "_strobe01",
            "_patch",
            "_patch2"
        };
        hiddenSelectionsMaterials[]=
        {
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat"
        };
        hiddenSelectionsTextures[]=
        {
            "",
            "aa_121_helmets\data\patch_aa_est_ir_co.paa",
            "aa_121_helmets\data\patch_aa_pj_co.paa"
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_soup: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Soup Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Comtac III";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor2",
        "_counterWeight",
        //"_pvs31Batt",
        "_Switch"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        //"",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_pol_ir_co.paa",
        "aa_121_helmets\data\patch_aa_soup_morale_co.paa",
        "",
        "",
        "",
        //"",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor2",
            "_counterWeight",
            //"_pvs31Batt",
            "_Switch"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            //"",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_pol_ir_co.paa",
            "aa_121_helmets\data\patch_aa_soup_morale_co.paa",
            "",
            "",
            "",
            //"",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_soup_off: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Soup Special' (Headset off)";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Comtac III";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor2",
        "_counterWeight",
        //"_pvs31Batt",
        "_Switch"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        //"",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_pol_ir_co.paa",
        "aa_121_helmets\data\patch_aa_soup_morale_co.paa",
        "",
        "",
        "",
        //"",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor2",
            "_counterWeight",
            //"_pvs31Batt",
            "_Switch"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            //"",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_pol_ir_co.paa",
            "aa_121_helmets\data\patch_aa_soup_morale_co.paa",
            "",
            "",
            "",
            //"",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_pyro: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Pyro Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_pvs31Batt",
        "_Switch",
        "_strobe01"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_pyro_morale_co.paa",
        "aa_121_helmets\data\patch_aa_pyro_co.paa",
        "",
        "",
        "",
        "",
        "",
        "121_75th_helmet\data\strobe_a_co.paa"
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_pvs31Batt",
            "_Switch",
            "_strobe01"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_pyro_morale_co.paa",
            "aa_121_helmets\data\patch_aa_pyro_co.paa",
            "",
            "",
            "",
            "",
            "",
            "121_75th_helmet\data\strobe_a_co.paa"
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_pyro_off: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Pyro Special' (Headset Off)'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_pvs31Batt",
        "_Switch",
        "_strobe01"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_pyro_morale_co.paa",
        "aa_121_helmets\data\patch_aa_pyro_co.paa",
        "",
        "",
        "",
        "",
        "",
        "121_75th_helmet\data\strobe_a_co.paa"
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_pvs31Batt",
            "_Switch",
            "_strobe01"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_pyro_morale_co.paa",
            "aa_121_helmets\data\patch_aa_pyro_co.paa",
            "",
            "",
            "",
            "",
            "",
            "121_75th_helmet\data\strobe_a_co.paa"
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_hibid: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Falklands Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_peltor2.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Comtac III";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_HelmetCam",
        "_pvs31Batt",
        "_chargepro"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_hibid_morale_co.paa",
        "aa_121_helmets\data\patch_aa_hibid_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_peltor2.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_HelmetCam",
            "_pvs31Batt",
            "_chargepro"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_hibid_morale_co.paa",
            "aa_121_helmets\data\patch_aa_hibid_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_hibid_off: ItemCore
{
    author="Visco";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Falklands Special' (Headset off)";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore_peltor2_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Comtac III";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_HelmetCam",
        "_pvs31Batt",
        "_chargepro"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_hibid_morale_co.paa",
        "aa_121_helmets\data\patch_aa_hibid_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore_peltor2_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_HelmetCam",
            "_pvs31Batt",
            "_chargepro"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_hibid_morale_co.paa",
            "aa_121_helmets\data\patch_aa_hibid_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_puotek: ItemCore
{
    author="Puotek";
    scope=2;
    ace_hearing_hasEHP=1;
    ace_hearing_lowerVolume=0;
    ace_hearing_protection=0.75;
    displayName="[AA] Ops-Core MT 'Puotek Special'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1.p3d";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset, Puotek's version";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_pvs31Batt",
        "_Switch"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\accs\amp\amp2.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_puotek_back_co.paa",
        "aa_121_helmets\data\patch_aa_puotek_right_co.paa",
        "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_hasEHP=1;
        ace_hearing_lowerVolume=0;
        ace_hearing_protection=0.75;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_pvs31Batt",
            "_Switch"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\accs\amp\amp2.rvmat",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_puotek_back_co.paa",
            "aa_121_helmets\data\patch_aa_puotek_right_co.paa",
            "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
class aa_opscore_puotek_off: ItemCore
{
    author="Puotek";
    scope=2;
    ace_hearing_protection=0;
    ace_hearing_lowerVolume=0;
    displayName="[AA] Ops-Core MT 'Puotek Special' (Headset Off)'";
    picture="\121_75th_helmet\121_ranger_helmet_ca.paa";
    model="\121_75th_helmet\75th_opscore1_off.p3d";
    Headlamps_Preset="Headlamps_Preset_Helmet_Surefire_HL1_Right_ARC";
    descriptionShort="Ops-Core MT, MC Cover, Ops-Core RAC Headset, Puotek's version";
    hiddenSelections[]=
    {
        "camo1",
        "_cover",
        "_patch",
        "_patch2",
        "_headsetRacs",
        "_peltor",
        "_peltor2",
        "_HelmetCam",
        "_pvs31Batt",
        "_Switch"
    };
    hiddenSelectionsMaterials[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
        "121_75th_helmet\data\cover.rvmat",
        "",
        "121_75th_helmet\data\ir_reflect.rvmat",
        "121_75th_helmet\data\accs\amp\amp2.rvmat",
        "",
        "",
        "",
        "",
        ""
    };
    hiddenSelectionsTextures[]=
    {
        "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
        "121_75th_helmet\data\price_helmet2_mc_co.paa",
        "aa_121_helmets\data\patch_aa_puotek_back_co.paa",
        "aa_121_helmets\data\patch_aa_puotek_right_co.paa",
        "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
        "",
        "",
        "",
        "",
        ""
    };
    class ItemInfo: HeadgearItem
    {
        mass=50;
        uniformModel="\121_75th_helmet\75th_opscore1_off.p3d";
        modelSides[]={3,1};
        armor=6;
        passThrough=0.4;
        ace_hearing_protection=0;
        ace_hearing_lowerVolume=0;
        hiddenSelections[]=
        {
            "camo1",
            "_cover",
            "_patch",
            "_patch2",
            "_headsetRacs",
            "_peltor",
            "_peltor2",
            "_HelmetCam",
            "_pvs31Batt",
            "_Switch"
        };
        hiddenSelectionsMaterials[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails.rvmat",
            "121_75th_helmet\data\cover.rvmat",
            "",
            "121_75th_helmet\data\ir_reflect.rvmat",
            "121_75th_helmet\data\accs\amp\amp2.rvmat",
            "",
            "",
            "",
            "",
            ""
        };
        hiddenSelectionsTextures[]=
        {
            "121_75th_helmet\data\highcut_ops_core_rails_co.paa",
            "121_75th_helmet\data\price_helmet2_mc_co.paa",
            "aa_121_helmets\data\patch_aa_puotek_back_co.paa",
            "aa_121_helmets\data\patch_aa_puotek_right_co.paa",
            "121_75th_helmet\data\accs\amp\opscore_amp2_mc_co.paa",
            "",
            "",
            "",
            "",
            ""
        };
        class HitpointsProtectionInfo
        {
            class Head
            {
                hitpointName="HitHead";
                armor=6;
                passThrough=0.4;
            };
        };
    };
};
*/
