class CfgPatches
{
	class TFL_pcu
	{
		units[]={};
		weapons[]={};
		requiredVersion=1;
		requiredAddons[]={};
	};
};
class UniformSlotInfo
{
	slotType=0;
	linkProxy="-";
};
class CfgVehicles
{
	class I_Soldier_base_F;
	class SoldierWB;
	class B_Soldier_F;
	class TFL_mw_pcu_mc_blk: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_blk_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_blk_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_rg: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_rg_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_rg_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_gry: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_gry";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_gry_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_gry_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_mc: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_mc_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_mc_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_tan: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_tan";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_mc_tan_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_mw_pcu_mc_tan_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_mc.paa",
			"TFL_g3\g3\Pants_mc.paa"
		};
	};
	class TFL_mw_pcu_aor1_blk: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_blk";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_blk_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_blk_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_rg: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_rg";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_rg_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_rg_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_gry: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_gry";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_gry_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_gry_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_mc: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_mc_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_mc_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_tan: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_tan";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor1_tan_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor1_tan_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_AOR1.paa",
			"TFL_g3\g3\Pants_AOR1.paa"
		};
	};
	class TFL_mw_pcu_aor2_blk: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_blk";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_blk_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_blk_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_rg: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_rg";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_rg_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_rg_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_gry: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_gry";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_gry_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_gry_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_mc: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_mc_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_mc_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_tan: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_tan";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_aor2_tan_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_aor2_tan_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_AOR2.paa",
			"TFL_g3\g3\Pants_AOR2.paa"
		};
	};
	class TFL_mw_pcu_m81_blk: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_blk";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_blk_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_blk_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_blk_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_rg: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_rg";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_rg_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_rg_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_rg_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_gry: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_gry";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_gry_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_gry_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_gry_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_mc: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_mc";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_mc_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_mc_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_mc_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_tan: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_tan";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
	class TFL_mw_pcu_m81_tan_g: B_Soldier_F
	{
		scope=2;
		camouflage=0;
		displayName="Rangers";
		scopeArsenal=2;
		faction="sof_rangers";
		author="TFL,Nidonreb";
		model="TFL_pcu\TFL_mw_pcu_g.p3d";
		_generalMacro="tfl_test";
		uniforMClass="TFL_pcu_m81_tan_g";
		identityTypes[]=
		{
			"G_NATO_diver"
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"leftknee",
			"rightknee"
		};
		hiddenSelectionsTextures[]=
		{
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_pcu\data\pcu_tan_co.paa",
			"TFL_g3\g3\Pants_M81.paa",
			"TFL_g3\g3\Pants_M81.paa"
		};
	};
};
class CfgWeapons
{
	class ItemCore;
	class UniformItem;
	class Uniform_Base;
	class tfl_mw_pcu_mc_blk_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCBLK)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_blk";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_blk_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCBLK/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_blk_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_rg_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCRG)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_rg";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_rg_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCRG/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_rg_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_gry_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCGRY)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_gry";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_gry_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCGRY/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_gry_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_mc_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCMC)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_mc";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_mc_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCMC/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_mc_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_tan_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCTAN)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_tan";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_mc_tan_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (MCTAN/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_mc_tan_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_blk_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1BLK)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_blk";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_blk_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1BLK/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_blk_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_rg_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1RG)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_rg";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_rg_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1RG/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_rg_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_gry_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1GRY)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_gry";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_gry_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1GRY/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_gry_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_mc_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1MC)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_mc";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_mc_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1MC/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_mc_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor1_tan_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR1TAN/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor1_tan_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_blk_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2BLK)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_blk";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_blk_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2BLK/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_blk_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_rg_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2RG)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_rg";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_rg_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2RG/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_rg_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_gry_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2GRY)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_gry";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_gry_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2GRY/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_gry_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_mc_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2MC)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_mc";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_mc_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2MC/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_mc_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_tan_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2TAN)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_tan";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_aor2_tan_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (AOR2TAN/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_aor2_tan_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_blk_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81BLK)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_blk";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_blk_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81BLK/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_blk_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_rg_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81RG)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_rg";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_rg_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81RG/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_rg_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_gry_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81GRY)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_gry";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_gry_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81GRY/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_gry_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_mc_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81MC)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_mc";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_mc_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81MC/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_mc_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_tan_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81TAN)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_tan";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
	class tfl_mw_pcu_m81_tan_g_uni: Uniform_Base
	{
		scope=2;
		scopeArsenal=2;
		author="TFL,Nidonreb";
		displayName="[TFL] G3 PCU (M81TAN/G)";
		picture="";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniforMClass="tfl_mw_pcu_m81_tan_g";
			containerClass="Supply100";
			mass=5;
			uniformType="Neopren";
		};
	};
};
class cfgMods
{
	author="Nidonreb";
	timepacked="1622065067";
};
