#include "BIS_AddonInfo.hpp"
// config.bin - 11:11:23 06/04/17, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class GeK_TLC100 {
		units[] = {"GeK_TLC100"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Soft_F"};
	};
};
class WeaponFireGun;	// External class reference
class WeaponCloudsGun;	// External class reference
class WeaponFireMGun;	// External class reference
class WeaponCloudsMGun;	// External class reference

class CfgVehicles {
	class Car;	// External class reference
	
	class Car_F : Car {
		class HitPoints {
			class HitLFWheel;	// External class reference
			class HitLF2Wheel;	// External class reference
			class HitRFWheel;	// External class reference
			class HitRF2Wheel;	// External class reference
			class HitBody;	// External class reference
			class HitGlass1;	// External class reference
			class HitGlass2;	// External class reference
			class HitGlass3;	// External class reference
			class HitGlass4;	// External class reference
		};
	};
	
	class GeK_TLC100 : Car_F {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 White";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC.paa"};
		terrainCoef = 0.5;
		turnCoef = 2.5;
		precision = 10;
		armor = 75;
		cost = 50000;
		transportMaxBackpacks = 10;
		transportSoldier = 3;
		wheelDamageRadiusCoef = 0.9;
		wheelDestroyRadiusCoef = 0.4;
		maxFordingDepth = 0.5;
		waterResistance = 2;
		crewCrashProtection = 0.1;
		driverLeftHandAnimName = "drivewheel";
		driverRightHandAnimName = "drivewheel";
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 4;
			};
		};
		
		class Turrets {};
		
		class HitPoints : HitPoints {
			class HitLFWheel : HitLFWheel {
				armor = 0.35;
				passThrough = 0;
			};
			
			class HitLF2Wheel : HitLF2Wheel {
				armor = 0.35;
				passThrough = 0;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.35;
				passThrough = 0;
			};
			
			class HitRF2Wheel : HitRF2Wheel {
				armor = 0.35;
				passThrough = 0;
			};
			
			class HitFuel {
				armor = 0.6;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 1.5;
				material = -1;
				name = "engine";
				visual = "";
				passThrough = 0;
			};
			
			class HitBody : HitBody {
				name = "karoserie";
				visual = "camo1";
				passThrough = 0;
			};
			
			class HitGlass1 : HitGlass1 {
				armor = 1;
			};
			
			class HitGlass2 : HitGlass2 {
				armor = 1;
			};
			
			class HitGlass3 : HitGlass3 {
				armor = 1;
			};
			
			class HitGlass4 : HitGlass4 {
				armor = 1;
			};
		};
		driverAction = "driver_low01";
		cargoAction[] = {"passenger_low01", "passenger_generic01_leanleft", "passenger_generic01_foldhands"};
		getInAction = "GetInLow";
		getOutAction = "GetOutLow";
		cargoGetInAction[] = {"GetInLow"};
		cargoGetOutAction[] = {"GetOutLow"};
		attenuationEffectType = "CarAttenuation";
		soundGetIn[] = {"A3\Sounds_F\vehicles\soft\Hatchback_01\Hatchback_01_door", 0.562341, 1};
		soundGetOut[] = {"A3\Sounds_F\vehicles\soft\Hatchback_01\Hatchback_01_door", 0.562341, 1, 40};
		soundDammage[] = {"", 0.562341, 1};
		soundEngineOnInt[] = {"cl3_sounds\cl3_vehicles\v12-lambo-fin\int_start.wav", 0.398107, 1};
		soundEngineOnExt[] = {"cl3_sounds\cl3_vehicles\v12-lambo-fin\ext_start.wav", 0.446684, 1, 200};
		soundEngineOffInt[] = {"cl3_sounds\cl3_vehicles\v12-lambo-fin\int_stop.wav", 0.398107, 1};
		soundEngineOffExt[] = {"cl3_sounds\cl3_vehicles\v12-lambo-fin\ext_stop.wav", 0.446684, 1, 200};
		buildCrash0[] = {"A3\Sounds_F\vehicles\soft\noises\crash_building_01", 0.707946, 1, 200};
		buildCrash1[] = {"A3\Sounds_F\vehicles\soft\noises\crash_building_02", 0.707946, 1, 200};
		buildCrash2[] = {"A3\Sounds_F\vehicles\soft\noises\crash_building_03", 0.707946, 1, 200};
		buildCrash3[] = {"A3\Sounds_F\vehicles\soft\noises\crash_building_04", 0.707946, 1, 200};
		soundBuildingCrash[] = {"buildCrash0", 0.25, "buildCrash1", 0.25, "buildCrash2", 0.25, "buildCrash3", 0.25};
		WoodCrash0[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_01", 0.707946, 1, 200};
		WoodCrash1[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_02", 0.707946, 1, 200};
		WoodCrash2[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_03", 0.707946, 1, 200};
		WoodCrash3[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_04", 0.707946, 1, 200};
		WoodCrash4[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_05", 0.707946, 1, 200};
		WoodCrash5[] = {"A3\Sounds_F\vehicles\soft\noises\crash_mix_wood_06", 0.707946, 1, 200};
		soundWoodCrash[] = {"woodCrash0", 0.166, "woodCrash1", 0.166, "woodCrash2", 0.166, "woodCrash3", 0.166, "woodCrash4", 0.166, "woodCrash5", 0.166};
		ArmorCrash0[] = {"A3\Sounds_F\vehicles\soft\noises\crash_vehicle_01", 0.707946, 1, 200};
		ArmorCrash1[] = {"A3\Sounds_F\vehicles\soft\noises\crash_vehicle_02", 0.707946, 1, 200};
		ArmorCrash2[] = {"A3\Sounds_F\vehicles\soft\noises\crash_vehicle_03", 0.707946, 1, 200};
		ArmorCrash3[] = {"A3\Sounds_F\vehicles\soft\noises\crash_vehicle_04", 0.707946, 1, 200};
		soundArmorCrash[] = {"ArmorCrash0", 0.25, "ArmorCrash1", 0.25, "ArmorCrash2", 0.25, "ArmorCrash3", 0.25};
		
		class Sounds {
			class Idle_ext {
				sound[] = {"GeK_TLC100\Sounds\idle\offroad_ext", 0.7, 1, 152};
				frequency = "0.95	+	((rpm/	3500) factor[(100/	3500),(600/	3500)])*0.15";
				volume = "engineOn*camPos*(((rpm/	3500) factor[(100/	3500),(200/	3500)])	*	((rpm/	3500) factor[(530/	3500),(380/	3500)]))";
			};
			
			class Engine {
				sound[] = {"GeK_TLC100\Sounds\engine\offroad_Ext", 0.7, 1, 200};
				frequency = "0.25	+	((rpm/	3500) factor[(300/	3500),(3500/	3500)])*0.7";
				volume = "1*engineOn*camPos*(thrust factor[0.1,1])*(((rpm/	3500) factor[(300/	3500),(500/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine_distance {
				sound[] = {"GeK_TLC100\Sounds\distances\offroad", 0.7, 1, 800};
				frequency = "0.25	+	((rpm/	3500) factor[(300/	3500),(3500/	3500)])*0.7";
				volume = "1*engineOn*camPos*(((rpm/	3500) factor[(300/	3500),(500/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine1_ext {
				sound[] = {"GeK_TLC100\Sounds\engine\car_off_Ext", 0.7, 1, 200};
				frequency = "0.25	+	((rpm/	3500) factor[(300/	3500),(3500/	3500)])*0.7";
				volume = "1*engineOn*camPos*(thrust factor[0.1,0])*(((rpm/	3500) factor[(300/	3500),(500/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine2_ext {
				sound[] = {"GeK_TLC100\Sounds\turbo\turbo", 0.7, 1, 50};
				frequency = "1";
				volume = "engineOn*camPos*(thrust factor[0.1,1])*(((rpm/	3500) factor[(1500/	3500),(3100/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine3_ext {
				sound[] = {"GeK_TLC100\Sounds\rev\rev_ext", 0.7, 1, 220};
				frequency = "0.95	+	((rpm/	3500) factor[(3000/	3500),(3500/	3500)])*0.1";
				volume = "engineOn*camPos*((rpm/	3500) factor[(3000/	3500),(3500/	3500)])";
			};
			
			class Engine4_ext {
				sound[] = {"GeK_TLC100\Sounds\engine\car_ext_high", 0.7, 1, 240};
				frequency = "1";
				volume = "0";
			};
			
			class Idle_int {
				sound[] = {"GeK_TLC100\Sounds\idle\offroad_int", 0.5, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(100/	3500),(600/	3500)])*0.15";
				volume = "engineOn*(1-camPos)*(((rpm/	3500) factor[(100/	3500),(200/	3500)])	*	((rpm/	3500) factor[(530/	3500),(380/	3500)]))";
			};
			
			class Engine_int {
				sound[] = {"GeK_TLC100\Sounds\engine\offroad_int", 0.5, 1};
				frequency = "0.25	+	((rpm/	3500) factor[(300/	3500),(3500/	3500)])*0.7";
				volume = "1*engineOn*(1-camPos)*(thrust factor[0.1,1])*(((rpm/	3500) factor[(300/	3500),(500/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine1_int {
				sound[] = {"GeK_TLC100\Sounds\engine\car_off_int", 0.5, 1};
				frequency = "0.25	+	((rpm/	3500) factor[(300/	3500),(3500/	3500)])*0.7";
				volume = "1*engineOn*(1-camPos)*(thrust factor[0.1,0])*(((rpm/	3500) factor[(300/	3500),(500/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine2_int {
				sound[] = {"GeK_TLC100\Sounds\turbo\turbo_int", 0.5, 1};
				frequency = "1";
				volume = "engineOn*(1-camPos)*(thrust factor[0.1,1])*(((rpm/	3500) factor[(1500/	3500),(3100/	3500)])	*	((rpm/	3500) factor[(3500/	3500),(3500/	3500)]))";
			};
			
			class Engine3_int {
				sound[] = {"GeK_TLC100\Sounds\rev\rev", 0.5, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(3000/	3500),(3500/	3500)])*0.1";
				volume = "engineOn*(1-camPos)*((rpm/	3500) factor[(3000/	3500),(3500/	3500)])";
			};
			
			class IdleThrust {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_1", 0.7, 1, 250};
				frequency = "0.95	+	((rpm/	3500) factor[(200/	3500),(580/	3500)])*0.15";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(200/	3500),(350/	3500)])	*	((rpm/	3500) factor[(580/	3500),(400/	3500)]))";
			};
			
			class EngineThrust {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_2", 0.7, 1, 250};
				frequency = "0.9	+	((rpm/	3500) factor[(380/	3500),(960/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(380/	3500),(580/	3500)])	*	((rpm/	3500) factor[(960/	3500),(700/	3500)]))";
			};
			
			class Engine1_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_3", 0.7, 1, 250};
				frequency = "0.9	+	((rpm/	3500) factor[(700/	3500),(1400/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(700/	3500),(970/	3500)])	*	((rpm/	3500) factor[(1400/	3500),(1100/	3500)]))";
			};
			
			class Engine2_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_4", 0.7, 1, 250};
				frequency = "0.9	+	((rpm/	3500) factor[(1100/	3500),(1860/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(1100/	3500),(1430/	3500)])	*	((rpm/	3500) factor[(1860/	3500),(1570/	3500)]))";
			};
			
			class Engine3_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_5", 0.7, 1, 250};
				frequency = "0.95	+	((rpm/	3500) factor[(1600/	3500),(2200/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(1600/	3500),(1860/	3500)])	*	((rpm/	3500) factor[(2200/	3500),(2050/	3500)]))";
			};
			
			class Engine4_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_6", 0.7, 1, 250};
				frequency = "0.95	+	((rpm/	3500) factor[(2040/	3500),(2670/	3500)]) *0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(2040/	3500),(2200/	3500)])	*	((rpm/	3500) factor[(2670/	3500),(2400/	3500)]))";
			};
			
			class Engine5_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_7", 0.7, 1, 250};
				frequency = "0.95	+	((rpm/	3500) factor[(2400/	3500),(3050/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(2400/	3500),(2660/	3500)])	*	((rpm/	3500) factor[(3050/	3500),(2800/	3500)]))";
			};
			
			class Engine6_Thrust_ext {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\ext_exhaust_7", 0.7, 1, 250};
				frequency = "0.95	+	((rpm/	3500) factor[(2700/	3500),(3500/	3500)])*0.2";
				volume = "engineOn*camPos*(0.7+(0.6*(thrust factor[0.1,1])))*((rpm/	3500) factor[(2700/	3500),(3200/	3500)])";
			};
			
			class IdleThrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_1", 0.5, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(200/	3500),(580/	3500)])*0.15";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(200/	3500),(350/	3500)])	*	((rpm/	3500) factor[(580/	3500),(400/	3500)]))";
			};
			
			class EngineThrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_2", 0.5, 1};
				frequency = "0.9	+	((rpm/	3500) factor[(380/	3500),(960/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(380/	3500),(580/	3500)])	*	((rpm/	3500) factor[(960/	3500),(700/	3500)]))";
			};
			
			class Engine1_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_3", 0.5, 1};
				frequency = "0.9	+	((rpm/	3500) factor[(700/	3500),(1400/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(700/	3500),(970/	3500)])	*	((rpm/	3500) factor[(1400/	3500),(1100/	3500)]))";
			};
			
			class Engine2_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_4", 0.7, 1};
				frequency = "0.9	+	((rpm/	3500) factor[(1100/	3500),(1860/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(1100/	3500),(1430/	3500)])	*	((rpm/	3500) factor[(1860/	3500),(1570/	3500)]))";
			};
			
			class Engine3_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_5", 0.7, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(1600/	3500),(2200/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(1600/	3500),(1860/	3500)])	*	((rpm/	3500) factor[(2200/	3500),(2050/	3500)]))";
			};
			
			class Engine4_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_6", 0.7, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(2040/	3500),(2670/	3500)]) *0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(2040/	3500),(2200/	3500)])	*	((rpm/	3500) factor[(2670/	3500),(2400/	3500)]))";
			};
			
			class Engine5_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_7", 0.7, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(2400/	3500),(3050/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*(((rpm/	3500) factor[(2400/	3500),(2660/	3500)])	*	((rpm/	3500) factor[(3050/	3500),(2800/	3500)]))";
			};
			
			class Engine6_Thrust_int {
				sound[] = {"GeK_TLC100\Sounds\Exhaust\Cars\int_exhaust_7", 0.7, 1};
				frequency = "0.95	+	((rpm/	3500) factor[(2700/	3500),(3500/	3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.7+(0.6*(thrust factor[0.1,1])))*((rpm/	3500) factor[(2700/	3500),(3200/	3500)])";
			};
			
			class Movement {
				sound = "soundEnviron";
				frequency = "1";
				volume = "0";
			};
			
			class TiresRockOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_1", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*rock*(speed factor[2, 20])";
			};
			
			class TiresSandOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-sand1", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_2", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*grass*(speed factor[2, 20])";
			};
			
			class TiresMudOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-mud2", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_gravel_1", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_asfalt_2", 0.501187, 1, 60};
				frequency = "1";
				volume = "camPos*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_ext_car_3", 0.398107, 1, 90};
				frequency = "1";
				volume = "camPos*(damper0 max 0.02)*(speed factor[0, 8])";
			};
			
			class TiresRockIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_1", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*rock*(speed factor[2, 20])";
			};
			
			class TiresSandIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-sand2", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_2", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*grass*(speed factor[2, 20])";
			};
			
			class TiresMudIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-mud2", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_gravel_1", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_asfalt_2", 0.501187, 1};
				frequency = "1";
				volume = "(1-camPos)*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_int_car_3", 0.251189, 1};
				frequency = "1";
				volume = "(damper0 max 0.1)*(speed factor[0, 8])*(1-camPos)";
			};
			
			class breaking_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04", 0.707946, 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class acceleration_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.707946, 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 2])";
			};
			
			class turn_left_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.707946, 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[2, 15])";
			};
			
			class turn_right_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", 0.707946, 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class breaking_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_14_dirt_breaking", 0.707946, 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class acceleration_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_16_dirt_acceleration", 0.707946, 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 1])";
			};
			
			class turn_left_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt", 0.707946, 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[1, 15])";
			};
			
			class turn_right_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt", 0.707946, 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class breaking_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class acceleration_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 2])";
			};
			
			class turn_left_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[2, 15])";
			};
			
			class turn_right_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class breaking_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_14_dirt_breaking_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(LongSlipDrive Factor[-01, -0.4])*(Speed Factor[2, 15])";
			};
			
			class acceleration_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_16_dirt_acceleration_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 2])";
			};
			
			class turn_left_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[2, 15])";
			};
			
			class turn_right_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt_int", 0.316228, 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
		};
		
		class RenderTargets {
			class LeftMirror {
				renderTarget = "rendertarget0";
				
				class CameraView1 {
					pointPosition = "PIP0_pos";
					pointDirection = "PIP0_dir";
					renderQuality = 5;
					renderVisionMode = 3;
					fov = 0.7;
				};
			};
			
			class RearCam {
				renderTarget = "rendertarget1";
				
				class CameraView1 {
					pointPosition = "PIP1_pos";
					pointDirection = "PIP1_dir";
					renderQuality = 5;
					renderVisionMode = 3;
					fov = 0.7;
				};
			};
			
			class FrontCam {
				renderTarget = "rendertarget2";
				
				class CameraView1 {
					pointPosition = "PIP2_pos";
					pointDirection = "PIP2_dir";
					renderQuality = 5;
					renderVisionMode = 3;
					fov = 0.7;
				};
			};
			
			class BackCam {
				renderTarget = "rendertarget3";
				
				class CameraView1 {
					pointPosition = "PIP3_pos";
					pointDirection = "PIP3_dir";
					renderQuality = 5;
					renderVisionMode = 0;
					fov = 0.7;
				};
			};
		};
		thrustDelay = 0.5;
		brakeIdleSpeed = 1.78;
		maxSpeed = 250;
		fuelCapacity = 20;
		wheelCircumference = 2.505;
		antiRollbarForceCoef = 2.5;
		antiRollbarForceLimit = 7;
		antiRollbarSpeedMin = 10;
		antiRollbarSpeedMax = 200;
		idleRpm = 600;
		redRpm = 4000;
		
		class complexGearbox {
			GearboxRatios[] = {"R1", -4, "N", 0, "D1", 3.5*(0.58^0), "D2", 4.5*(0.58^1), "D3", 5*(0.58^2), "D4", 5*(0.58^3), "D5", 5*(0.59^4), "D6", 5*(0.6^5)};
			TransmissionRatios[] = {"High", 7};
			gearBoxMode = "auto";
			moveOffGear = 1;
			driveString = "D";
			neutralString = "N";
			reverseString = "R";
			gearUpMaxCoef = 0.95;
			gearDownMaxCoef = 0.85;
			gearUpMinCoef = 0.65;
			gearDownMinCoef = 0.55;
			transmissionDelay = 2;
		};
		simulation = "carx";
		dampersBumpCoef = 3;
		differentialType = "all_limited";
		frontRearSplit = 0.5;
		frontBias = 1.5;
		rearBias = 1.5;
		centreBias = 1.3;
		clutchStrength = 20;
		enginePower = 600;
		maxOmega = 450;
		peakTorque = 425;
		dampingRateFullThrottle = 0.08;
		dampingRateZeroThrottleClutchEngaged = 0.5;
		dampingRateZeroThrottleClutchDisengaged = 0.35;
		torqueCurve[] = {{(0/3500), (0/425)}, {(500/3500), (200/425)}, {(1500/3500), (405/425)}, {(2000/3500), (425/425)}, {(2500/3500), (350/425)}, {(3000/3500), (300/425)}, {(6000/3500), (0/425)}};
		changeGearMinEffectivity[] = {1, 0.15, 1, 1, 1, 1, 1, 1};
		switchTime = 0.31;
		latency = 1.5;
		
		class Wheels {
			class LF {
				boneName = "wheel_1_1_damper";
				steering = 1;
				side = "left";
				center = "wheel_1_1_axis";
				boundary = "wheel_1_1_bound";
				width = 0.2;
				mass = 50;
				MOI = 5.3;
				dampingRate = 0.5;
				maxBrakeTorque = 5000;
				maxHandBrakeTorque = 0;
				suspTravelDirection[] = {0, -1, 0};
				suspForceAppPointOffset = "wheel_1_1_axis";
				tireForceAppPointOffset = "wheel_1_1_axis";
				maxCompression = 0.1;
				mMaxDroop = 0.05;
				sprungMass = 272.5;
				springStrength = 27250;
				springDamperRate = 6725;
				longitudinalStiffnessPerUnitGravity = 100000;
				latStiffX = 25;
				latStiffY = 18000;
				frictionVsSlipGraph[] = {{0, 1}, {0.5, 1}, {1, 1}};
			};
			
			class LR : LF {
				boneName = "wheel_1_2_damper";
				steering = 0;
				center = "wheel_1_2_axis";
				boundary = "wheel_1_2_bound";
				suspForceAppPointOffset = "wheel_1_2_axis";
				tireForceAppPointOffset = "wheel_1_2_axis";
				maxHandBrakeTorque = 4000;
			};
			
			class RF : LF {
				boneName = "wheel_2_1_damper";
				center = "wheel_2_1_axis";
				boundary = "wheel_2_1_bound";
				suspForceAppPointOffset = "wheel_2_1_axis";
				tireForceAppPointOffset = "wheel_2_1_axis";
				steering = 1;
				side = "right";
			};
			
			class RR : RF {
				boneName = "wheel_2_2_damper";
				steering = 0;
				center = "wheel_2_2_axis";
				boundary = "wheel_2_2_bound";
				suspForceAppPointOffset = "wheel_2_2_axis";
				tireForceAppPointOffset = "wheel_2_2_axis";
				maxHandBrakeTorque = 4000;
			};
		};
		memoryPointTrackFLL = "TrackFLL";
		memoryPointTrackFLR = "TrackFLR";
		memoryPointTrackBLL = "TrackBLL";
		memoryPointTrackBLR = "TrackBLR";
		memoryPointTrackFRL = "TrackFRL";
		memoryPointTrackFRR = "TrackFRR";
		memoryPointTrackBRL = "TrackBRL";
		memoryPointTrackBRR = "TrackBRR";
		
		class Library {
			libTextDesc = "";
		};
		
		class Damage {
			tex[] = {};
			mat[] = {"cl3_vehiclefunctions\skins\skin.rvmat", "cl3_vehiclefunctions\skins\skin_damage.rvmat", "cl3_vehiclefunctions\skins\skin_destruct.rvmat", "cl3_vehiclefunctions\glass\glass.rvmat", "cl3_vehiclefunctions\glass\glass_damage.rvmat", "cl3_vehiclefunctions\glass\glass_destruct.rvmat"};
		};
		
		class Exhausts {
			class Exhaust1 {
				position = "exhaust1_pos";
				direction = "exhaust1_dir";
				effect = "ExhaustEffectOffroad";
			};
			
			class Exhaust2 {
				position = "exhaust2_pos";
				direction = "exhaust2_dir";
				effect = "ExhaustEffectHTruck";
			};
		};
		
		class Reflectors {
			class LightCarHeadL01 {
				color[] = {1900, 1800, 1700};
				ambient[] = {5, 5, 5};
				position = "LightCarHeadL01";
				direction = "LightCarHeadL01_end";
				hitpoint = "Light_L";
				selection = "Light_L";
				size = 1;
				innerAngle = 100;
				outerAngle = 179;
				coneFadeCoef = 10;
				intensity = 1;
				useFlare = 1;
				dayLight = 0;
				flareSize = 1;
				
				class Attenuation {
					start = 1;
					constant = 0;
					linear = 0;
					quadratic = 0.25;
					hardLimitStart = 30;
					hardLimitEnd = 60;
				};
			};
			
			class LightCarHeadL02 : LightCarHeadL01 {
				position = "LightCarHeadL02";
				direction = "LightCarHeadL02_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadR01 : LightCarHeadL01 {
				position = "LightCarHeadR01";
				direction = "LightCarHeadR01_end";
				hitpoint = "Light_R";
				selection = "Light_R";
			};
			
			class LightCarHeadR02 : LightCarHeadR01 {
				position = "LightCarHeadR02";
				direction = "LightCarHeadR02_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadL03 : LightCarHeadL01 {
				position = "LightCarHeadL03";
				direction = "LightCarHeadL03_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadR03 : LightCarHeadR01 {
				position = "LightCarHeadR03";
				direction = "LightCarHeadR03_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadL04 : LightCarHeadL01 {
				position = "LightCarHeadL04";
				direction = "LightCarHeadL04_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadR04 : LightCarHeadR01 {
				position = "LightCarHeadR04";
				direction = "LightCarHeadR04_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadL05 : LightCarHeadL01 {
				position = "LightCarHeadL05";
				direction = "LightCarHeadL05_end";
				FlareSize = 0.8;
			};
			
			class LightCarHeadR05 : LightCarHeadR01 {
				position = "LightCarHeadR05";
				direction = "LightCarHeadR05_end";
				FlareSize = 0.8;
			};
		};
		aggregateReflectors[] = {{"LightCarHeadL01", "LightCarHeadL02", "LightCarHeadL03", "LightCarHeadL04", "LightCarHeadL05", "LightCarHeadL06", "LightCarHeadL07"}, {"LightCarHeadR01", "LightCarHeadR02", "LightCarHeadR02", "LightCarHeadR03", "LightCarHeadR05", "LightCarHeadR06", "LightCarHeadR07"}};
	};
	
	class GeK_TLC100_2 : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & Igor Victoria";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 by Igor Victoria v1";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC2.paa"};
	};
	
	class GeK_TLC100_3 : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & Igor Victoria";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 by Igor Victoria v2";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC3.paa"};
	};
	
	class GeK_TLC100_4 : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & spunindarkness";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 by spunindarkness";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC4.paa"};
	};
	
	class GeK_TLC100_Tan : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 Tan";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_Tan.paa"};
	};
	
	class GeK_TLC100_Green : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 Green";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_Green.paa"};
	};
	
	class GeK_TLC100_Black : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 Black";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_Black.paa"};
	};
	
	class GeK_TLC100_Nato : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 NATO Woodland";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_NATO.paa"};
	};
	
	class GeK_TLC100_Nato_Tan : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 NATO Tan";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_NATO_Tan.paa"};
	};
	
	class GeK_TLC100_Red : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 Red";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_Red.paa"};
	};
	
	class GeK_TLC100_Brown : GeK_TLC100 {
		model = "\GeK_TLC100\GeK_TLC100";
		author = "Forester & GeK & Wirk & LTF";
		scope = 2;
		crew = "C_man_1";
		side = 3;
		faction = CIV_F;
		displayName = "Toyota LC 100 Brown";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"GeK_TLC100\Data\TLC_Brown.paa"};
	};
	
};

class cfgMods {
	author = 76561198018721225;
	timepacked = 1430406374;
};
